// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/product/v1/product_service.proto

package productv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Money represents a monetary value
type Money struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount in smallest currency unit (e.g., cents for USD)
	Amount int64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Currency code (e.g., "USD", "EUR")
	Currency      string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// Discount represents a discount value object
type Discount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        *Money                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"` // Percentage as decimal (e.g., 0.10 = 10%)
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Discount) Reset() {
	*x = Discount{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discount) ProtoMessage() {}

func (x *Discount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discount.ProtoReflect.Descriptor instead.
func (*Discount) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{1}
}

func (x *Discount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Discount) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Discount) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Discount) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

// Product represents a product entity
type Product struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category       string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	BasePrice      *Money                 `protobuf:"bytes,5,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	EffectivePrice *Money                 `protobuf:"bytes,6,opt,name=effective_price,json=effectivePrice,proto3" json:"effective_price,omitempty"` // Calculated price after discount
	Discount       *Discount              `protobuf:"bytes,7,opt,name=discount,proto3" json:"discount,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // "active" or "inactive"
	ArchivedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetBasePrice() *Money {
	if x != nil {
		return x.BasePrice
	}
	return nil
}

func (x *Product) GetEffectivePrice() *Money {
	if x != nil {
		return x.EffectivePrice
	}
	return nil
}

func (x *Product) GetDiscount() *Discount {
	if x != nil {
		return x.Discount
	}
	return nil
}

func (x *Product) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Product) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateProductRequest represents the request to create a product
type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	BasePrice     *Money                 `protobuf:"bytes,4,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProductRequest) GetBasePrice() *Money {
	if x != nil {
		return x.BasePrice
	}
	return nil
}

// CreateProductResponse represents the response from creating a product
type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProductResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// UpdateProductRequest represents the request to update a product
type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Category      *string                `protobuf:"bytes,4,opt,name=category,proto3,oneof" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

// UpdateProductResponse represents the response from updating a product
type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProductResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// GetProductRequest represents the request to get a product
type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// GetProductResponse represents the response from getting a product
type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// ListProductsRequest represents the request to list products
type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *string                `protobuf:"bytes,1,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Status        *string                `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListProductsRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *ListProductsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProductsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ListProductsResponse represents the response from listing products
type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ApplyDiscountRequest represents the request to apply a discount
type ApplyDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Discount      *Discount              `protobuf:"bytes,2,opt,name=discount,proto3" json:"discount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyDiscountRequest) Reset() {
	*x = ApplyDiscountRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDiscountRequest) ProtoMessage() {}

func (x *ApplyDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDiscountRequest.ProtoReflect.Descriptor instead.
func (*ApplyDiscountRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{11}
}

func (x *ApplyDiscountRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ApplyDiscountRequest) GetDiscount() *Discount {
	if x != nil {
		return x.Discount
	}
	return nil
}

// ApplyDiscountResponse represents the response from applying a discount
type ApplyDiscountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyDiscountResponse) Reset() {
	*x = ApplyDiscountResponse{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDiscountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDiscountResponse) ProtoMessage() {}

func (x *ApplyDiscountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDiscountResponse.ProtoReflect.Descriptor instead.
func (*ApplyDiscountResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{12}
}

func (x *ApplyDiscountResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// RemoveDiscountRequest represents the request to remove a discount
type RemoveDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDiscountRequest) Reset() {
	*x = RemoveDiscountRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDiscountRequest) ProtoMessage() {}

func (x *RemoveDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDiscountRequest.ProtoReflect.Descriptor instead.
func (*RemoveDiscountRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveDiscountRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// RemoveDiscountResponse represents the response from removing a discount
type RemoveDiscountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDiscountResponse) Reset() {
	*x = RemoveDiscountResponse{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDiscountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDiscountResponse) ProtoMessage() {}

func (x *RemoveDiscountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDiscountResponse.ProtoReflect.Descriptor instead.
func (*RemoveDiscountResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveDiscountResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// ActivateProductRequest represents the request to activate a product
type ActivateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateProductRequest) Reset() {
	*x = ActivateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProductRequest) ProtoMessage() {}

func (x *ActivateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProductRequest.ProtoReflect.Descriptor instead.
func (*ActivateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{15}
}

func (x *ActivateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// ActivateProductResponse represents the response from activating a product
type ActivateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateProductResponse) Reset() {
	*x = ActivateProductResponse{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProductResponse) ProtoMessage() {}

func (x *ActivateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProductResponse.ProtoReflect.Descriptor instead.
func (*ActivateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{16}
}

func (x *ActivateProductResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// DeactivateProductRequest represents the request to deactivate a product
type DeactivateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductRequest) Reset() {
	*x = DeactivateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductRequest) ProtoMessage() {}

func (x *DeactivateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductRequest.ProtoReflect.Descriptor instead.
func (*DeactivateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{17}
}

func (x *DeactivateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// DeactivateProductResponse represents the response from deactivating a product
type DeactivateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductResponse) Reset() {
	*x = DeactivateProductResponse{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductResponse) ProtoMessage() {}

func (x *DeactivateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductResponse.ProtoReflect.Descriptor instead.
func (*DeactivateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{18}
}

func (x *DeactivateProductResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// ArchiveProductRequest represents the request to archive a product
type ArchiveProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveProductRequest) Reset() {
	*x = ArchiveProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveProductRequest) ProtoMessage() {}

func (x *ArchiveProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveProductRequest.ProtoReflect.Descriptor instead.
func (*ArchiveProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{19}
}

func (x *ArchiveProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// ArchiveProductResponse represents the response from archiving a product
type ArchiveProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveProductResponse) Reset() {
	*x = ArchiveProductResponse{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveProductResponse) ProtoMessage() {}

func (x *ArchiveProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveProductResponse.ProtoReflect.Descriptor instead.
func (*ArchiveProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{20}
}

func (x *ArchiveProductResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

var File_proto_product_v1_product_service_proto protoreflect.FileDescriptor

const file_proto_product_v1_product_service_proto_rawDesc = "" +
	"\n" +
	"&proto/product/v1/product_service.proto\x12\n" +
	"product.v1\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\x05Money\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xb7\x01\n" +
	"\bDiscount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x06amount\x18\x02 \x01(\v2\x11.product.v1.MoneyR\x06amount\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xd6\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x120\n" +
	"\n" +
	"base_price\x18\x05 \x01(\v2\x11.product.v1.MoneyR\tbasePrice\x12:\n" +
	"\x0feffective_price\x18\x06 \x01(\v2\x11.product.v1.MoneyR\x0eeffectivePrice\x120\n" +
	"\bdiscount\x18\a \x01(\v2\x14.product.v1.DiscountR\bdiscount\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12;\n" +
	"\varchived_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"archivedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9a\x01\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x120\n" +
	"\n" +
	"base_price\x18\x04 \x01(\v2\x11.product.v1.MoneyR\tbasePrice\"6\n" +
	"\x15CreateProductResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\xbc\x01\n" +
	"\x14UpdateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x04 \x01(\tH\x02R\bcategory\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_category\"6\n" +
	"\x15UpdateProductResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"2\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"C\n" +
	"\x12GetProductResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"\x99\x01\n" +
	"\x13ListProductsRequest\x12\x1f\n" +
	"\bcategory\x18\x01 \x01(\tH\x00R\bcategory\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\tH\x01R\x06status\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offsetB\v\n" +
	"\t_categoryB\t\n" +
	"\a_status\"]\n" +
	"\x14ListProductsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.product.v1.ProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"g\n" +
	"\x14ApplyDiscountRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x120\n" +
	"\bdiscount\x18\x02 \x01(\v2\x14.product.v1.DiscountR\bdiscount\"6\n" +
	"\x15ApplyDiscountResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"6\n" +
	"\x15RemoveDiscountRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"7\n" +
	"\x16RemoveDiscountResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"7\n" +
	"\x16ActivateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"8\n" +
	"\x17ActivateProductResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"9\n" +
	"\x18DeactivateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\":\n" +
	"\x19DeactivateProductResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"6\n" +
	"\x15ArchiveProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"7\n" +
	"\x16ArchiveProductResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId2\xa2\x06\n" +
	"\x0eProductService\x12T\n" +
	"\rCreateProduct\x12 .product.v1.CreateProductRequest\x1a!.product.v1.CreateProductResponse\x12T\n" +
	"\rUpdateProduct\x12 .product.v1.UpdateProductRequest\x1a!.product.v1.UpdateProductResponse\x12K\n" +
	"\n" +
	"GetProduct\x12\x1d.product.v1.GetProductRequest\x1a\x1e.product.v1.GetProductResponse\x12Q\n" +
	"\fListProducts\x12\x1f.product.v1.ListProductsRequest\x1a .product.v1.ListProductsResponse\x12T\n" +
	"\rApplyDiscount\x12 .product.v1.ApplyDiscountRequest\x1a!.product.v1.ApplyDiscountResponse\x12W\n" +
	"\x0eRemoveDiscount\x12!.product.v1.RemoveDiscountRequest\x1a\".product.v1.RemoveDiscountResponse\x12Z\n" +
	"\x0fActivateProduct\x12\".product.v1.ActivateProductRequest\x1a#.product.v1.ActivateProductResponse\x12`\n" +
	"\x11DeactivateProduct\x12$.product.v1.DeactivateProductRequest\x1a%.product.v1.DeactivateProductResponse\x12W\n" +
	"\x0eArchiveProduct\x12!.product.v1.ArchiveProductRequest\x1a\".product.v1.ArchiveProductResponseB)Z'catalog-proj/proto/product/v1;productv1b\x06proto3"

var (
	file_proto_product_v1_product_service_proto_rawDescOnce sync.Once
	file_proto_product_v1_product_service_proto_rawDescData []byte
)

func file_proto_product_v1_product_service_proto_rawDescGZIP() []byte {
	file_proto_product_v1_product_service_proto_rawDescOnce.Do(func() {
		file_proto_product_v1_product_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_v1_product_service_proto_rawDesc), len(file_proto_product_v1_product_service_proto_rawDesc)))
	})
	return file_proto_product_v1_product_service_proto_rawDescData
}

var file_proto_product_v1_product_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_product_v1_product_service_proto_goTypes = []any{
	(*Money)(nil),                     // 0: product.v1.Money
	(*Discount)(nil),                  // 1: product.v1.Discount
	(*Product)(nil),                   // 2: product.v1.Product
	(*CreateProductRequest)(nil),      // 3: product.v1.CreateProductRequest
	(*CreateProductResponse)(nil),     // 4: product.v1.CreateProductResponse
	(*UpdateProductRequest)(nil),      // 5: product.v1.UpdateProductRequest
	(*UpdateProductResponse)(nil),     // 6: product.v1.UpdateProductResponse
	(*GetProductRequest)(nil),         // 7: product.v1.GetProductRequest
	(*GetProductResponse)(nil),        // 8: product.v1.GetProductResponse
	(*ListProductsRequest)(nil),       // 9: product.v1.ListProductsRequest
	(*ListProductsResponse)(nil),      // 10: product.v1.ListProductsResponse
	(*ApplyDiscountRequest)(nil),      // 11: product.v1.ApplyDiscountRequest
	(*ApplyDiscountResponse)(nil),     // 12: product.v1.ApplyDiscountResponse
	(*RemoveDiscountRequest)(nil),     // 13: product.v1.RemoveDiscountRequest
	(*RemoveDiscountResponse)(nil),    // 14: product.v1.RemoveDiscountResponse
	(*ActivateProductRequest)(nil),    // 15: product.v1.ActivateProductRequest
	(*ActivateProductResponse)(nil),   // 16: product.v1.ActivateProductResponse
	(*DeactivateProductRequest)(nil),  // 17: product.v1.DeactivateProductRequest
	(*DeactivateProductResponse)(nil), // 18: product.v1.DeactivateProductResponse
	(*ArchiveProductRequest)(nil),     // 19: product.v1.ArchiveProductRequest
	(*ArchiveProductResponse)(nil),    // 20: product.v1.ArchiveProductResponse
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
}
var file_proto_product_v1_product_service_proto_depIdxs = []int32{
	0,  // 0: product.v1.Discount.amount:type_name -> product.v1.Money
	21, // 1: product.v1.Discount.start_date:type_name -> google.protobuf.Timestamp
	21, // 2: product.v1.Discount.end_date:type_name -> google.protobuf.Timestamp
	0,  // 3: product.v1.Product.base_price:type_name -> product.v1.Money
	0,  // 4: product.v1.Product.effective_price:type_name -> product.v1.Money
	1,  // 5: product.v1.Product.discount:type_name -> product.v1.Discount
	21, // 6: product.v1.Product.archived_at:type_name -> google.protobuf.Timestamp
	21, // 7: product.v1.Product.created_at:type_name -> google.protobuf.Timestamp
	21, // 8: product.v1.Product.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 9: product.v1.CreateProductRequest.base_price:type_name -> product.v1.Money
	2,  // 10: product.v1.GetProductResponse.product:type_name -> product.v1.Product
	2,  // 11: product.v1.ListProductsResponse.products:type_name -> product.v1.Product
	1,  // 12: product.v1.ApplyDiscountRequest.discount:type_name -> product.v1.Discount
	3,  // 13: product.v1.ProductService.CreateProduct:input_type -> product.v1.CreateProductRequest
	5,  // 14: product.v1.ProductService.UpdateProduct:input_type -> product.v1.UpdateProductRequest
	7,  // 15: product.v1.ProductService.GetProduct:input_type -> product.v1.GetProductRequest
	9,  // 16: product.v1.ProductService.ListProducts:input_type -> product.v1.ListProductsRequest
	11, // 17: product.v1.ProductService.ApplyDiscount:input_type -> product.v1.ApplyDiscountRequest
	13, // 18: product.v1.ProductService.RemoveDiscount:input_type -> product.v1.RemoveDiscountRequest
	15, // 19: product.v1.ProductService.ActivateProduct:input_type -> product.v1.ActivateProductRequest
	17, // 20: product.v1.ProductService.DeactivateProduct:input_type -> product.v1.DeactivateProductRequest
	19, // 21: product.v1.ProductService.ArchiveProduct:input_type -> product.v1.ArchiveProductRequest
	4,  // 22: product.v1.ProductService.CreateProduct:output_type -> product.v1.CreateProductResponse
	6,  // 23: product.v1.ProductService.UpdateProduct:output_type -> product.v1.UpdateProductResponse
	8,  // 24: product.v1.ProductService.GetProduct:output_type -> product.v1.GetProductResponse
	10, // 25: product.v1.ProductService.ListProducts:output_type -> product.v1.ListProductsResponse
	12, // 26: product.v1.ProductService.ApplyDiscount:output_type -> product.v1.ApplyDiscountResponse
	14, // 27: product.v1.ProductService.RemoveDiscount:output_type -> product.v1.RemoveDiscountResponse
	16, // 28: product.v1.ProductService.ActivateProduct:output_type -> product.v1.ActivateProductResponse
	18, // 29: product.v1.ProductService.DeactivateProduct:output_type -> product.v1.DeactivateProductResponse
	20, // 30: product.v1.ProductService.ArchiveProduct:output_type -> product.v1.ArchiveProductResponse
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_product_v1_product_service_proto_init() }
func file_proto_product_v1_product_service_proto_init() {
	if File_proto_product_v1_product_service_proto != nil {
		return
	}
	file_proto_product_v1_product_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_product_v1_product_service_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_v1_product_service_proto_rawDesc), len(file_proto_product_v1_product_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_v1_product_service_proto_goTypes,
		DependencyIndexes: file_proto_product_v1_product_service_proto_depIdxs,
		MessageInfos:      file_proto_product_v1_product_service_proto_msgTypes,
	}.Build()
	File_proto_product_v1_product_service_proto = out.File
	file_proto_product_v1_product_service_proto_goTypes = nil
	file_proto_product_v1_product_service_proto_depIdxs = nil
}
